# Generated by Django 6.0.6 on 2026-07-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_category_remove_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComfortBeyondTimeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image1', models.ImageField(upload_to='cbt_section/')),
                ('image2', models.ImageField(upload_to='cbt_section/')),
            ],
            options={
                'verbose_name': 'Comfort Beyond Time Section',
                'verbose_name_plural': 'Comfort Beyond Time Sections',
            },
        ),
    ]
