# Generated by Django 6.0.6 on 2026-07-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('address_link', models.URLField(max_length=500)),
                ('link_text', models.CharField(default='View on Map', max_length=100)),
            ],
        ),
    ]
