# Generated by Django 6.0.6 on 2026-07-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_footermenu_footersection_footermenuitem_sociallink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footersection',
            old_name='copyright_text',
            new_name='copyright_line_1',
        ),
        migrations.AddField(
            model_name='footersection',
            name='copyright_line_2',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
