# Generated by Django 6.0.6 on 2026-07-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero_slides/mobile/'),
        ),
    ]
