# Generated by Django 6.0.6 on 2026-07-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_product_is_bestseller_product_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='products/details/'),
        ),
        migrations.AddField(
            model_name='product',
            name='detail_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='products/details/'),
        ),
        migrations.AddField(
            model_name='product',
            name='detail_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='products/details/'),
        ),
        migrations.AddField(
            model_name='product',
            name='detail_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='products/details/'),
        ),
        migrations.AddField(
            model_name='product',
            name='detail_image_5',
            field=models.ImageField(blank=True, null=True, upload_to='products/details/'),
        ),
        migrations.AddField(
            model_name='product',
            name='detail_image_6',
            field=models.ImageField(blank=True, null=True, upload_to='products/details/'),
        ),
        migrations.AddField(
            model_name='product',
            name='detail_image_7',
            field=models.ImageField(blank=True, null=True, upload_to='products/details/'),
        ),
        migrations.AddField(
            model_name='product',
            name='detail_image_8',
            field=models.ImageField(blank=True, null=True, upload_to='products/details/'),
        ),
        migrations.AddField(
            model_name='product',
            name='detail_image_9',
            field=models.ImageField(blank=True, null=True, upload_to='products/details/'),
        ),
    ]
