# Generated by Django 6.0.6 on 2026-07-07 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_blogcategory_blog_excerpt_blog_is_trending_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='is_trending',
        ),
    ]
