# Generated by Django 6.0.6 on 2026-07-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_category_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_on_navbar',
            field=models.BooleanField(default=True),
        ),
    ]
